defmodule Catalyst.Plugins.ElixirBaseTest do
  use Catalyst.TestSupport.ProjectCase, async: true
  alias Catalyst.Plugins.ElixirBase
  alias Catalyst.Actions

  test "generates a standard OTP application" do
    execution =
      test_execution("my_app", app_name: "my_app", app_module: "MyApp", otp_app: :my_app)

    actions = ElixirBase.run(execution)

    assert Enum.map(actions, fn {mod, _opts} -> mod end) == [
             Actions.MixTask,
             Actions.MixTask,
             Actions.AddFile
           ]

    assert {Actions.MixTask, new_opts} = Enum.at(actions, 0)
    assert Keyword.get(new_opts, :name) == "new"
    assert Keyword.get(new_opts, :args) == ["my_app", "--sup"]

    assert {Actions.MixTask, deps_opts} = Enum.at(actions, 1)
    assert Keyword.get(deps_opts, :name) == "deps.get"
    assert Keyword.get(deps_opts, :args) == nil

    assert {Actions.AddFile, readme_opts} = Enum.at(actions, 2)
    assert Keyword.get(readme_opts, :path) == "README.md"
    content = Keyword.fetch!(readme_opts, :content)
    assert String.contains?(content, "generated by Catalyst")
  end

  test "can disable supervision tree" do
    execution =
      test_execution("simple_lib", app_name: "simple_lib", app_module: "MyApp", otp_app: :my_app)

    actions = ElixirBase.run(execution, sup: false)

    # Verify --sup flag is missing
    assert {Actions.MixTask, new_opts} = Enum.at(actions, 0)
    assert Keyword.get(new_opts, :name) == "new"
    assert Keyword.get(new_opts, :args) == ["simple_lib"]
    refute "--sup" in Keyword.get(new_opts, :args, [])
  end

  test "does not scaffold when targeting existing project" do
    execution =
      test_execution("my_app",
        app_name: "my_app",
        app_module: "MyApp",
        otp_app: :my_app,
        mode: :existing
      )

    actions = ElixirBase.run(execution)

    assert actions == []
  end
end
