defmodule Catalyst.Plugins.ElixirBaseTest do
  use Catalyst.TestSupport.ProjectCase, async: true
  alias Catalyst.Plugins.ElixirBase
  alias Catalyst.Actions

  test "generates a standard OTP application" do
    execution =
      test_execution("my_app", app_name: "my_app", app_module: "MyApp", otp_app: :my_app)

    actions = ElixirBase.run(execution)

    assert [%Actions.MixTask{}, %Actions.MixTask{}, %Actions.AddFile{}] = actions

    assert %Actions.MixTask{name: "new", args: ["my_app", "--sup"]} =
             Enum.at(actions, 0)

    assert %Actions.MixTask{name: "deps.get", args: nil} =
             Enum.at(actions, 1)

    assert %Actions.AddFile{path: "README.md", content: content} = Enum.at(actions, 2)
    assert String.contains?(content, "generated by Catalyst")
  end

  test "can disable supervision tree" do
    execution =
      test_execution("simple_lib", app_name: "simple_lib", app_module: "MyApp", otp_app: :my_app)

    actions = ElixirBase.run(execution, sup: false)

    # Verify --sup flag is missing
    assert %Actions.MixTask{name: "new", args: ["simple_lib"]} = Enum.at(actions, 0)
    refute "--sup" in Enum.at(actions, 0).args
  end

  test "does not scaffold when targeting existing project" do
    execution =
      test_execution("my_app",
        app_name: "my_app",
        app_module: "MyApp",
        otp_app: :my_app,
        mode: :existing
      )

    actions = ElixirBase.run(execution)

    assert actions == []
  end
end
