defmodule Catalyst.Plugin.ElixirBaseTest do
  use ExUnit.Case, async: true
  alias Catalyst.Plugin.ElixirBase
  alias Catalyst.Actions
  alias Catalyst.Execution

  test "generates a standard OTP application" do
    execution = Execution.new(app_path: "my_app", app_name: "my_app")

    actions = ElixirBase.run(execution) |> Catalyst.Plugin.normalize_actions()

    assert [%Actions.MixTask{}, %Actions.MixTask{}, %Actions.AddFile{}] = actions

    assert %Actions.MixTask{name: "new", args: ["my_app", "--sup"]} =
             Enum.at(actions, 0)

    assert %Actions.MixTask{name: "deps.get", args: nil} =
             Enum.at(actions, 1)

    assert %Actions.AddFile{path: "README.md", content: content} = Enum.at(actions, 2)
    assert String.contains?(content, "generated by Catalyst")
  end

  test "can disable supervision tree" do
    execution = Execution.new(app_path: "simple_lib", app_name: "simple_lib")

    actions = ElixirBase.run(execution, sup: false) |> Catalyst.Plugin.normalize_actions()

    # Verify --sup flag is missing
    assert %Actions.MixTask{name: "new", args: ["simple_lib"]} = Enum.at(actions, 0)
    refute "--sup" in Enum.at(actions, 0).args
  end

  test "does not scaffold when targeting existing project" do
    execution = Execution.new(app_path: "my_app", app_name: "my_app", mode: :existing)

    actions = ElixirBase.run(execution) |> Catalyst.Plugin.normalize_actions()

    assert actions == []
  end
end
