defmodule Catalyst.Plugin.ElixirBaseTest do
  use ExUnit.Case, async: true
  alias Catalyst.Plugin.ElixirBase
  alias Catalyst.Action

  test "generates a standard OTP application" do
    opts = [app_path: "my_app"]

    actions = ElixirBase.run(opts) |> Catalyst.Plugin.normalize_actions()

    assert [%Action.SystemCommand{}, %Action.SystemCommand{}, %Action.AddFile{}] = actions

    assert %Action.SystemCommand{cmd: "mix", args: ["new", "my_app", "--sup"]} =
             Enum.at(actions, 0)

    assert %Action.SystemCommand{cmd: "mix", args: ["deps.get"], cd: "my_app"} =
             Enum.at(actions, 1)

    assert %Action.AddFile{path: "my_app/README.md", content: content} = Enum.at(actions, 2)
    assert String.contains?(content, "generated by Catalyst")
  end

  test "can disable supervision tree" do
    opts = [app_path: "simple_lib", sup: false]

    actions = ElixirBase.run(opts) |> Catalyst.Plugin.normalize_actions()

    # Verify --sup flag is missing
    assert %Action.SystemCommand{cmd: "mix", args: ["new", "simple_lib"]} = Enum.at(actions, 0)
    refute "--sup" in Enum.at(actions, 0).args
  end

  test "does not scaffold when targeting existing project" do
    opts = [app_path: "my_app", mode: :existing]

    actions = ElixirBase.run(opts) |> Catalyst.Plugin.normalize_actions()

    assert actions == []
  end
end
