defmodule Catalyst.Plugins.ElixirBase do
  use Catalyst.Plugin
  alias Catalyst.Execution

  @impl true
  def run(execution, opts \\ []) do
    if Execution.mode(execution) == :existing do
      []
    else
      # Default to creating a supervision tree (--sup) unless explicitly disabled
      flags = if opts[:sup] == false, do: [], else: ["--sup"]
      app_path = Execution.app_path(execution)
      app_name = Execution.app_name(execution) || app_path

      [
        %Actions.MixTask{name: "new", args: [app_path] ++ flags},
        %Actions.MixTask{name: "deps.get"},
        %Actions.AddFile{
          path: "README.md",
          content: "# #{app_name}\n\nThis is an Elixir application generated by Catalyst."
        }
      ]
    end
  end
end
