defmodule Catalyst.Plugins.PhoenixBase do
  use Catalyst.Plugin
  alias Catalyst.Error
  alias Catalyst.Execution

  @impl true
  def run(execution, opts \\ []) do
    if Execution.mode(execution) == :existing do
      []
    else
      flags = opts |> Keyword.get(:flags, []) |> flags_to_argv()
      app_path = Execution.app_path(execution)
      app_name = Execution.app_name(execution) || app_path

      [
        %Actions.MixTask{name: "phx.new", args: [app_path | flags]},
        %Actions.MixTask{name: "deps.get"},
        %Actions.AddFile{
          path: "README.md",
          content: "# #{app_name}\n\nThis is a Phoenix application generated by Catalyst."
        }
      ]
    end
  end

  @impl true
  def post_validate(execution, _opts) do
    if Execution.mode(execution) == :existing do
      []
    else
      [
        %Catalyst.ValidationAction{
          action: %Actions.Function{
            module: __MODULE__,
            function: :validate_scaffolded_project!,
            args: [execution]
          }
        }
      ]
    end
  end

  def validate_scaffolded_project!(execution) do
    app_root = Execution.app_root(execution)
    mix_file = Path.join(app_root, "mix.exs")
    lock_file = Path.join(app_root, "mix.lock")

    cond do
      not File.exists?(mix_file) ->
        raise Error,
          code: :phx_scaffold_missing,
          reason: :missing_mix_file,
          context: %{path: mix_file}

      not File.exists?(lock_file) ->
        raise Error,
          code: :deps_lock_missing,
          reason: :missing_lock_file,
          context: %{path: lock_file}

      true ->
        :ok
    end
  end

  defp flags_to_argv(flags) when is_map(flags), do: flags |> Enum.to_list() |> flags_to_argv()

  defp flags_to_argv(flags) when is_list(flags) do
    Enum.flat_map(flags, &flag_to_argv/1)
  end

  defp flags_to_argv(_), do: []

  defp flag_to_argv({_key, nil}), do: []

  defp flag_to_argv({key, value}) when is_boolean(value) do
    name = normalize_flag_name(key)

    cond do
      value ->
        ["--#{name}"]

      String.starts_with?(name, "no-") ->
        ["--#{String.trim_leading(name, "no-")}"]

      true ->
        ["--no-#{name}"]
    end
  end

  defp flag_to_argv({key, value}), do: ["--#{normalize_flag_name(key)}", to_string(value)]

  defp flag_to_argv(flag) when is_binary(flag), do: [flag]

  defp flag_to_argv(flag) when is_atom(flag), do: ["--#{normalize_flag_name(flag)}"]

  defp flag_to_argv(_), do: []

  defp normalize_flag_name(key) do
    key
    |> to_string()
    |> String.trim_leading("--")
    |> String.replace("_", "-")
  end
end
