defmodule Catalyst.Plugin.ElixirBase do
  use Catalyst.Plugin

  @impl true
  def run(execution, opts \\ []) do
    if execution.mode == :existing do
      []
    else
      # Default to creating a supervision tree (--sup) unless explicitly disabled
      flags = if opts[:sup] == false, do: [], else: ["--sup"]
      app_path = execution.app_path
      app_name = execution.app_name || execution.app_path

      [
        %Actions.MixTask{name: "new", args: [app_path] ++ flags},
        %Actions.MixTask{name: "deps.get"},
        %Actions.AddFile{
          path: "README.md",
          content: "# #{app_name}\n\nThis is an Elixir application generated by Catalyst."
        }
      ]
    end
  end
end
