defmodule Catalyst.Plugin.ElixirBase do
  use Catalyst.Plugin

  @impl true
  def run(opts) do
    # Default to creating a supervision tree (--sup) unless explicitly disabled
    flags = if opts[:sup] == false, do: [], else: ["--sup"]

    [
      {Action.SystemCommand, cmd: "mix", args: ["new", opts[:app_path]] ++ flags},
      {Action.SystemCommand, cmd: "mix", args: ["deps.get"], cd: opts[:app_path]},
      {Action.AddFile,
       path: Path.join(opts[:app_path], "README.md"),
       content: "# #{opts[:app_name]}\n\nThis is an Elixir application generated by Catalyst."}
    ]
  end
end
