defmodule Catalyst.Plugin.ElixirBase do
  use Catalyst.Plugin

  @impl true
  def run(opts) do
    if opts[:mode] == :existing do
      []
    else
      # Default to creating a supervision tree (--sup) unless explicitly disabled
      flags = if opts[:sup] == false, do: [], else: ["--sup"]

      [
        {Actions.SystemCommand, cmd: "mix", args: ["new", opts[:app_path]] ++ flags},
        {Actions.SystemCommand, cmd: "mix", args: ["deps.get"], cd: opts[:app_path]},
        {Actions.AddFile,
         path: Path.join(opts[:app_path], "README.md"),
         content: "# #{opts[:app_name]}\n\nThis is an Elixir application generated by Catalyst."}
      ]
    end
  end
end
