defmodule Catalyst.Plugin.PhoenixBase do
  use Catalyst.Plugin

  @impl true
  def run(opts) do
    if opts[:mode] == :existing do
      []
    else
      flags = opts |> Keyword.get(:flags, []) |> flags_to_argv()

      [
        %Actions.SystemCommand{
          cmd: "mix",
          args: ["phx.new", opts[:app_path] | flags]
        },
        %Actions.SystemCommand{
          cmd: "mix",
          args: ["deps.get"],
          cd: opts[:app_path]
        },
        %Actions.AddFile{
          path: Path.join(opts[:app_path], "README.md"),
          content: "# #{opts[:app_name]}\n\nThis is a Phoenix application generated by Catalyst."
        }
      ]
    end
  end

  defp flags_to_argv(flags) when is_map(flags), do: flags |> Enum.to_list() |> flags_to_argv()

  defp flags_to_argv(flags) when is_list(flags) do
    Enum.flat_map(flags, &flag_to_argv/1)
  end

  defp flags_to_argv(_), do: []

  defp flag_to_argv({_key, nil}), do: []

  defp flag_to_argv({key, value}) when is_boolean(value) do
    name = normalize_flag_name(key)

    cond do
      value ->
        ["--#{name}"]

      String.starts_with?(name, "no-") ->
        ["--#{String.trim_leading(name, "no-")}"]

      true ->
        ["--no-#{name}"]
    end
  end

  defp flag_to_argv({key, value}), do: ["--#{normalize_flag_name(key)}", to_string(value)]

  defp flag_to_argv(flag) when is_binary(flag), do: [flag]

  defp flag_to_argv(flag) when is_atom(flag), do: ["--#{normalize_flag_name(flag)}"]

  defp flag_to_argv(_), do: []

  defp normalize_flag_name(key) do
    key
    |> to_string()
    |> String.trim_leading("--")
    |> String.replace("_", "-")
  end
end
