defmodule Catalyst.Plugin.PhoenixBase do
  use Catalyst.Plugin

  @impl true
  def run(opts) do
    [
      %Action.SystemCommand{
        cmd: "mix",
        args: ["phx.new", opts[:app_path], "--no-install"]
      },
      %Action.SystemCommand{
        cmd: "mix",
        args: ["deps.get"],
        cd: opts[:app_path]
      },
      %Action.AddFile{
        path: Path.join(opts[:app_path], "README.md"),
        content: "# #{opts[:app_name]}\n\nThis is a Phoenix application generated by Catalyst."
      }
    ]
  end
end
